/**
 * Standardised picklists for Industry and Department.
 * Used across job forms, candidate profiles, and filters.
 */

export const INDUSTRIES = [
  'Aerospace & Defense',
  'Agriculture & Farming',
  'Artificial Intelligence & ML',
  'Automotive & Transportation',
  'Aviation & Airports',
  'Banking & Financial Services',
  'Biotechnology & Life Sciences',
  'Chemical & Materials',
  'Construction & Real Estate',
  'Consumer Goods & FMCG',
  'Cybersecurity',
  'Defense & Military',
  'E-commerce & Marketplace',
  'Education & EdTech',
  'Energy & Utilities',
  'Entertainment & Media',
  'Environmental Services & Sustainability',
  'Fashion & Apparel',
  'FinTech',
  'Food & Beverage',
  'Gaming',
  'Government & Public Sector',
  'Healthcare & Hospitals',
  'HealthTech & MedTech',
  'Hospitality & Tourism',
  'Human Resources & Staffing',
  'Information Technology',
  'Infrastructure & Smart Cities',
  'Insurance & InsurTech',
  'Legal & Compliance',
  'Logistics & Supply Chain',
  'Manufacturing & Engineering',
  'Marine & Shipping',
  'Mining & Metals',
  'Non-Profit & NGO',
  'Oil & Gas',
  'Pharmaceuticals',
  'Professional Services & Consulting',
  'Publishing & Content',
  'Retail',
  'Research & Development',
  'SaaS & Software Products',
  'Space Technology',
  'Sports & Recreation',
  'Telecommunications',
  'Textiles',
  'Travel & Transportation',
  'Waste Management & Recycling',
];

export const DEPARTMENTS = [
  'Administration & Office Management',
  'Business Development',
  'Cloud & Infrastructure',
  'Customer Service & Support',
  'Data & Analytics',
  'Design & UX/UI',
  'DevOps & Site Reliability',
  'Engineering & Technology',
  'Finance & Accounting',
  'Human Resources',
  'IT & Software Development',
  'Legal & Compliance',
  'Logistics & Operations',
  'Marketing & Communications',
  'Operations',
  'Procurement & Supply Chain',
  'Product Management',
  'Quality Assurance & Testing',
  'Research & Development',
  'Sales',
  'Security',
  'Strategy & Consulting',
  'Training & Learning',
];
