export const SOURCE_LABELS = {
  platform    : 'Platform',
  career_page : 'Career Page',
  linkedin    : 'LinkedIn',
  naukri      : 'Naukri',
  indeed      : 'Indeed',
  glassdoor   : 'Glassdoor',
  monster     : 'Monster',
  shine       : 'Shine',
  social_media: 'Social Media',
  referral    : 'Referral',
  direct      : 'Direct',
  invite      : 'Invite',
  talent_match: 'Talent Match',
  manual      : 'Manual Add',
  resume_upload: 'Resume Upload',
  bulk_import : 'Bulk Import',
  admin_assign: 'Admin Assign',
  invite_link : 'Invite Link',
  others      : 'Others',
};

export const SOURCE_ICONS = {
  platform    : '💻',
  career_page : '🏢',
  linkedin    : '🔗',
  naukri      : '📋',
  indeed      : '🔍',
  glassdoor   : '🪟',
  monster     : '👾',
  shine       : '✨',
  social_media: '📱',
  social      : '📱',
  referral    : '👥',
  direct      : '📩',
  invite      : '✉️',
  invite_link : '✉️',
  talent_match: '🎯',
  manual      : '✏️',
  resume_upload: '📄',
  bulk_import : '📦',
  admin_assign: '👤',
  others      : '🌐',
  other       : '🌐',
};

export const SOURCE_COLORS = {
  platform    : '#014486',
  career_page : '#ef4444',
  linkedin    : '#0A66C2',
  naukri      : '#FF6B35',
  indeed      : '#2164F3',
  glassdoor   : '#0CAA41',
  monster     : '#6600CC',
  shine       : '#F59E0B',
  social_media: '#E1306C',
  referral    : '#06b6d4',
  direct      : '#94a3b8',
  invite      : '#10b981',
  invite_link : '#10b981',
  talent_match: '#7c3aed',
  manual      : '#0176D3',
  resume_upload: '#7c3aed',
  bulk_import : '#F59E0B',
  admin_assign: '#64748b',
  others      : '#9CA3AF',
};

export const SOURCE_OPTIONS = [
  { value: '', label: 'All sources' },
  { value: 'platform', label: SOURCE_LABELS.platform },
  { value: 'career_page', label: SOURCE_LABELS.career_page },
  { value: 'linkedin', label: SOURCE_LABELS.linkedin },
  { value: 'naukri', label: SOURCE_LABELS.naukri },
  { value: 'indeed', label: SOURCE_LABELS.indeed },
  { value: 'glassdoor', label: SOURCE_LABELS.glassdoor },
  { value: 'monster', label: SOURCE_LABELS.monster },
  { value: 'shine', label: SOURCE_LABELS.shine },
  { value: 'social_media', label: SOURCE_LABELS.social_media },
  { value: 'referral', label: SOURCE_LABELS.referral },
  { value: 'direct', label: SOURCE_LABELS.direct },
  { value: 'invite', label: SOURCE_LABELS.invite },
  { value: 'admin_assign', label: SOURCE_LABELS.admin_assign },
  { value: 'manual', label: SOURCE_LABELS.manual },
  { value: 'bulk_import', label: SOURCE_LABELS.bulk_import },
  { value: 'resume_upload', label: SOURCE_LABELS.resume_upload },
  { value: 'others', label: SOURCE_LABELS.others },
];

export const DEFAULT_SOURCES = Object.keys(SOURCE_LABELS);

export function sourceLabel(src) {
  return SOURCE_LABELS[src] || (src ? src.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) : '—');
}
